dataset_path: 'data/datasets.pkl'
data_dir: 'datasets'
checkpoint_path: 'best_models'
learning_rate: 0.0001
bottleneck_dim: 231
batch_size: 512
reconstruction_loss_weight: 0.7395403657181384
classification_loss_weight: 0.2532481787637928
dropout: 0.2882066987034187
num_lstm_layers: 2
conv1_out_channels: 64
conv2_out_channels: 128
dataset_subset: 'all'
dataset: 'dataset_a'
target_label: 'category'
num_classes: 5
overlap: 0.75
val_split: 0.10
max_epochs: 500
min_epochs: 5
num_workers: 4
sequence_length: 10000
early_stopping_patience: 10
learning_rate_patience: 3
monitor_metric: 'val_loss'
seed: 42
accumulate_grad_batches: 5
workers: 4
memory: '4GB'
chunk_size: 10
