dataset_path: 'data/datasets.pkl'
data_dir: 'datasets'
checkpoint_path: 'best_models'
learning_rate: 0.0001
bottleneck_dim: 256
batch_size: 32
model_name: 'classifier'
base_model: 'parallel_cnn_lstm'
reconstruction_loss_weight: 0.7395403657181384
classification_loss_weight: 0.2532481787637928
dropout: 0.2882066987034187
num_lstm_layers: 2
conv1_out_channels: 64
conv2_out_channels: 128
dataset_subset: 'all'
dataset: 'dataset_b'
target_label: 'device'
num_classes: 4
overlap: 0.0
val_split: 0.10
max_epochs: 100
min_epochs: 5
num_workers: 4
sequence_length: 10000
early_stopping_patience: 10
learning_rate_patience: 3
monitor_metric: 'val_loss'
seed: 42
accumulate_grad_batches: 2
workers: 4
memory: '4GB'
chunk_size: 10
kfold: 10
max_samples_per_class: 1000

# lstm config
# lstm_input_dim: 10000
# lstm_output_dim: 4
lstm_dropout: 0.2
lstm_hidden_dim: 256
lstm_num_layers: 2
lstm_bidirectional: False
