DATASET_PATH: 'data/datasets.pkl'
CHECKPOINT_PATH: 'best_models'
LEARNING_RATE: 0.0001
BOTTLENECK_DIM: 499
BATCH_SIZE: 512
RECONSTRUCTION_LOSS_WEIGHT: 0.7505276624416299
CLASSIFICATION_LOSS_WEIGHT: 0.3287720406316457
DROPOUT: 0.14658551588963611
NUM_CLASSES: 5
OVERLAP: 0.75
VAL_SPLIT: 0.10
MAX_EPOCHS: 500
MIN_EPOCHS: 5
NUM_WORKERS: 4
WINDOW_SIZE: 1000
EARLY_STOPPING_PATIENCE: 10
LEARNING_RATE_PATIENCE: 3
MONITOR_METRIC: 'val_loss'
SEED: 42
ACCUMULATE_GRAD_BATCHES: 5
